### ISSUE TITLE
Problem with Baidu link

### ISSUE THREAD

**Issue by grdsvt** [PureHing/face-mask-detection-tf2#1]
Hi, 
I would test this code but I have problem to connect to Baidu link to download your revision.
Can you give me other link to download?
My mail is grdsalvo@gmail.com
Thnaks for your availability

**Comment by PureHing** [comment]
@grdsvt Link：[https://pan.baidu.com/s/1hi5dV6kOs0wYxwupyqmHuQ ](https://pan.baidu.com/s/1hi5dV6kOs0wYxwupyqmHuQ )
code：wzb3

**Comment by grdsvt** [comment]
I tried.....bat connection with Baidu is very poor and I can't download it.
Can you use google drive or other link?
My mail is grdsalvo@gmail.com
Thanks for your availability

**Comment by grdsvt** [comment]
Or can you post your correction in GitHub?
I know that this problem is for all users are not in China, so can you describe these corrections here and download files here?
Thanks

**Comment by PureHing** [comment]
@grdsvt Thank you for your suggestion, I will update some wrong questions tomorrow.

**Comment by grdsvt** [comment]
Thank you for your cooperation.

**Comment by grdsvt** [comment]
Thanks for your availability

**Comment by millermuttu** [comment]
@grdsvt can you please share the data with me to 
my mail id is mullermuttu@gmail.com
