### ISSUE TITLE
Can you provide the pretrained models in future ?

### ISSUE THREAD

**Issue by masouduut94** [PureHing/face-mask-detection-tf2#15]
The code is great and straightforward.
I just thought to make it more popular just:

1 - add the pretrained models (just like you shared the data).
2 - Give recommendation on how we probably can boost up the performance. (like changing the kernels, change the backbone or etc ...)

Thanks

**Comment by PureHing** [comment]
1.Training from scratch without using pretrained models.You can try it by yourself
2.If you are deployment on the k210, using distillation technology is a good way.
