### ISSUE TITLE
Change resolution of video

### ISSUE THREAD

**Issue by grdsvt** [PureHing/face-mask-detection-tf2#3]
Hi, 
I would change resolution of captured video.
I see that now it is 320x240 in the interference.py.
I tried to change to 640x480 but I had problems in the run.
Can you help me to do this?
Thanks

**Comment by grdsvt** [comment]
Hi, is it possible to change resolution to 640x480 ?
I trained but I had errors.
Thanks

**Comment by PureHing** [comment]
@grdsvt Can you attach your error? It can be run at 640 * 480 during testing. Only need to modify input size and anchors... , training at 640*480 is also possible.

**Comment by grdsvt** [comment]
Hi, sorry I changed horizontal with vertical dimension......this was my error.
Now it is all ok
