### ISSUE TITLE
For working with GPU

### ISSUE THREAD

**Issue by grdsvt** [PureHing/face-mask-detection-tf2#4]
Hi, I would use with GPU but I have problem with Jetson Nano.
Is it necessary setting something to work with GPU and tensorflow?
I am using the trained model.

Thansk
Regards

**Comment by PureHing** [comment]
I am not familiar with Jetson Nano and just have used Raspberry Pi. you may need to verify your gpu environment with Jetson Nano Board first, install tensorflow-gpu..., and then coding to adjust my model.

**Comment by grdsvt** [comment]
So, you used Raspberry? I suppose Raspberry 4.0
I am using python 3.6.9 with tensorflow 2.1.0. Correct?

**Comment by PureHing** [comment]
Yes. Raspberry pi4(cpu) with tensorflow objection API.

**Comment by grdsvt** [comment]
Hi, I am testing your code with a jetson nano but I have very low fps.......0,5fps.
What is your average fps on Raspberry v.4?

Thnaks.

**Comment by grdsvt** [comment]
Hi,
I have no good results on jetson nano, so i would try with raspberry.
Please, can you help me?
Which is your fps on raspberry v.4?
Did you change something?

Thanks

**Comment by PureHing** [comment]
You should optimize the model with TensorRT and run inferencing on the Jetson Nano DevKit. I did not run this repo model on the Raspberry Pi 4, but tested mobilenetv2-ssdlite, which can reach 3 fps, and the  CPU usage is 50%.This repo model is smaller than this, and I guess there is a better frame rate.But I think jeston nano with tensorrt is better.If you want to improve the frame rate,Considering model quantification.

**Comment by grdsvt** [comment]
Hi, 
can we evaluate this work together. 
I am searching partner to optize the code, can you help me?
Can you send me mail?
Thanks

**Comment by PureHing** [comment]
Sorry, I don’t have much spare time because of the job is heavily.
