### ISSUE TITLE
cant download the dataset

### ISSUE THREAD

**Issue by millermuttu** [PureHing/face-mask-detection-tf2#5]
Hi, thanks for such a wonderful link. but i am not able to download the dataset from given link. please help or upload it google drive. 

thank you.

**Comment by PureHing** [comment]
@millermuttu  [google drive](https://drive.google.com/open?id=1KVoipQ-VsmF3FDil2QiZgJD1_Nnf02XW)

**Comment by millermuttu** [comment]
thank you so much:)
