### ISSUE TITLE
inference on video or camera is not working

### ISSUE THREAD

**Issue by millermuttu** [PureHing/face-mask-detection-tf2#6]
I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Dimensions must be equal, but are 52960 and 4420 for 'mul_1' (op: 'Mul') with input shapes: [52960,2], [4420,2].

i am getting this error while running inference on camera.

**Comment by PureHing** [comment]
please verify your input image size for priors anchors and camera resolution.
